const Checkered= {
    "id": 0,
    "content": [
        {
            "type": "square",
            "id": 1738424331559,
            "x": 0,
            "y": 0,
            "fill": "black",
            "fontSize": 12,
            "radius": 1,
            "width": 64,
            "height": 64,
            "scaleX": 2,
            "scaleY": 2,
            "angle": 0,
            "opacity": 1
        },
        {
            "type": "square",
            "id": 1738424543591,
            "x": 128,
            "y": 128,
            "width": 64,
            "radius": 1,
            "height": 64,
            "angle": 0,
            "fontSize": 12,
            "fill": "black",
            "scaleX": 2,
            "scaleY": 2,
            "opacity": 1,
            "stroke": null,
            "strokeWidth": 1,
            "points": []
        },
        {
            "type": "square",
            "id": 1738424568871,
            "x": 0,
            "y": 256,
            "width": 64,
            "radius": 1,
            "height": 64,
            "angle": 0,
            "fontSize": 12,
            "fill": "black",
            "scaleX": 2,
            "scaleY": 2,
            "opacity": 1,
            "stroke": null,
            "strokeWidth": 1,
            "points": []
        },
        {
            "type": "square",
            "id": 1738424610591,
            "x": 128,
            "y": 384,
            "width": 64,
            "radius": 1,
            "height": 64,
            "angle": 0,
            "fontSize": 12,
            "fill": "black",
            "scaleX": 2,
            "scaleY": 2,
            "opacity": 1,
            "stroke": null,
            "strokeWidth": 1,
            "points": []
        },
        {
            "type": "square",
            "id": 1738424672783,
            "x": 0,
            "y": 512,
            "width": 64,
            "radius": 1,
            "height": 64,
            "angle": 0,
            "fontSize": 12,
            "fill": "black",
            "scaleX": 2,
            "scaleY": 2,
            "opacity": 1,
            "stroke": null,
            "strokeWidth": 1,
            "points": []
        },
        {
            "type": "square",
            "id": 1738424770415,
            "x": 256,
            "y": 0,
            "width": 64,
            "radius": 1,
            "height": 64,
            "angle": 0,
            "fontSize": 12,
            "fill": "black",
            "scaleX": 2,
            "scaleY": 2,
            "opacity": 1,
            "stroke": null,
            "strokeWidth": 1,
            "points": []
        },
        {
            "type": "square",
            "id": 1738424794879,
            "x": 512,
            "y": 0,
            "width": 64,
            "radius": 1,
            "height": 64,
            "angle": 0,
            "fontSize": 12,
            "fill": "black",
            "scaleX": 2,
            "scaleY": 2,
            "opacity": 1,
            "stroke": null,
            "strokeWidth": 1,
            "points": []
        },
        {
            "type": "square",
            "id": 1738424807430,
            "x": 768,
            "y": 0,
            "width": 64,
            "radius": 1,
            "height": 64,
            "angle": 0,
            "fontSize": 12,
            "fill": "black",
            "scaleX": 2,
            "scaleY": 2,
            "opacity": 1,
            "stroke": null,
            "strokeWidth": 1,
            "points": []
        },
        {
            "type": "square",
            "id": 1738424822902,
            "x": 256,
            "y": 256,
            "width": 64,
            "radius": 1,
            "height": 64,
            "angle": 0,
            "fontSize": 12,
            "fill": "black",
            "scaleX": 2,
            "scaleY": 2,
            "opacity": 1,
            "stroke": null,
            "strokeWidth": 1,
            "points": []
        },
        {
            "type": "square",
            "id": 1738425055751,
            "x": 256,
            "y": 512,
            "width": 64,
            "radius": 1,
            "height": 64,
            "angle": 0,
            "fontSize": 12,
            "fill": "black",
            "scaleX": 2,
            "scaleY": 2,
            "opacity": 1,
            "stroke": null,
            "strokeWidth": 1,
            "points": []
        },
        {
            "type": "square",
            "id": 1738425095375,
            "x": 384,
            "y": 128,
            "width": 64,
            "radius": 1,
            "height": 64,
            "angle": 0,
            "fontSize": 12,
            "fill": "black",
            "scaleX": 2,
            "scaleY": 2,
            "opacity": 1,
            "stroke": null,
            "strokeWidth": 1,
            "points": []
        },
        {
            "type": "square",
            "id": 1738425105071,
            "x": 384,
            "y": 384,
            "width": 64,
            "radius": 1,
            "height": 64,
            "angle": 0,
            "fontSize": 12,
            "fill": "black",
            "scaleX": 2,
            "scaleY": 2,
            "opacity": 1,
            "stroke": null,
            "strokeWidth": 1,
            "points": []
        },
        {
            "type": "square",
            "id": 1738425115031,
            "x": 512,
            "y": 512,
            "width": 64,
            "radius": 1,
            "height": 64,
            "angle": 0,
            "fontSize": 12,
            "fill": "black",
            "scaleX": 2,
            "scaleY": 2,
            "opacity": 1,
            "stroke": null,
            "strokeWidth": 1,
            "points": []
        },
        {
            "type": "square",
            "id": 1738425139294,
            "x": 768,
            "y": 256,
            "width": 64,
            "radius": 1,
            "height": 64,
            "angle": 0,
            "fontSize": 12,
            "fill": "black",
            "scaleX": 2,
            "scaleY": 2,
            "opacity": 1,
            "stroke": null,
            "strokeWidth": 1,
            "points": []
        },
        {
            "type": "square",
            "id": 1738425149942,
            "x": 640,
            "y": 128,
            "width": 64,
            "radius": 1,
            "height": 64,
            "angle": 0,
            "fontSize": 12,
            "fill": "black",
            "scaleX": 2,
            "scaleY": 2,
            "opacity": 1,
            "stroke": null,
            "strokeWidth": 1,
            "points": []
        },
        {
            "type": "square",
            "id": 1738425229302,
            "x": 512,
            "y": 256,
            "width": 64,
            "radius": 1,
            "height": 64,
            "angle": 0,
            "fontSize": 12,
            "fill": "black",
            "scaleX": 2,
            "scaleY": 2,
            "opacity": 1,
            "stroke": null,
            "strokeWidth": 1,
            "points": []
        },
        {
            "type": "square",
            "id": 1738425238815,
            "x": 640,
            "y": 384,
            "width": 64,
            "radius": 1,
            "height": 64,
            "angle": 0,
            "fontSize": 12,
            "fill": "black",
            "scaleX": 2,
            "scaleY": 2,
            "opacity": 1,
            "stroke": null,
            "strokeWidth": 1,
            "points": []
        },
        {
            "type": "square",
            "id": 1738425273021,
            "x": 768,
            "y": 512,
            "width": 64,
            "radius": 1,
            "height": 64,
            "angle": 0,
            "fontSize": 12,
            "fill": "black",
            "scaleX": 2,
            "scaleY": 2,
            "opacity": 1,
            "stroke": null,
            "strokeWidth": 1,
            "points": []
        },
        {
            "type": "square",
            "id": 1738425300718,
            "x": 192,
            "y": 128,
            "width": 64,
            "radius": 1,
            "height": 64,
            "angle": 0,
            "fontSize": 12,
            "fill": "black",
            "scaleX": 8,
            "scaleY": 6,
            "opacity": 1,
            "stroke": "#FFFFFF",
            "strokeWidth": 1,
            "points": []
        },
        {
            "type": "text",
            "id": 1738425380335,
            "x": 235,
            "y": 165,
            "fill": "#ffffff",
            "fontSize": 64,
            "radius": 1,
            "width": 414.875,
            "height": 72.32,
            "text": "Insert Text Here",
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "opacity": 1
        }
    ],
    "backgroundColor": "#ffffff",
    "text": ""
};
export default Checkered;