const MovieMadness = {
  {
    "id": 0,
    "content": [
        {
            "type": "square",
            "id": 1737904734702,
            "x": 0,
            "y": -64,
            "fill": "#c33c36",
            "fontSize": 12,
            "radius": 1,
            "width": 200,
            "height": 200,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "opacity": 1
        },
        {
            "type": "square",
            "id": 1737904752510,
            "x": 200,
            "y": -64,
            "width": 200,
            "radius": 1,
            "height": 200,
            "angle": 0,
            "fontSize": 12,
            "fill": "#fefbfb",
            "scaleX": 1,
            "scaleY": 1,
            "opacity": 1
        },
        {
            "type": "square",
            "id": 1737904762701,
            "x": 400,
            "y": -64,
            "width": 200,
            "radius": 1,
            "height": 200,
            "angle": 0,
            "fontSize": 12,
            "fill": "#c33c36",
            "scaleX": 1,
            "scaleY": 1,
            "opacity": 1
        },
        {
            "type": "square",
            "id": 1737904772231,
            "x": 600,
            "y": -64,
            "width": 200,
            "radius": 1,
            "height": 200,
            "angle": 0,
            "fontSize": 12,
            "fill": "#fefbfb",
            "scaleX": 1,
            "scaleY": 1,
            "opacity": 1
        },
        {
            "type": "square",
            "id": 1737904780157,
            "x": 0,
            "y": 478,
            "width": 200,
            "radius": 1,
            "height": 200,
            "angle": 0,
            "fontSize": 12,
            "fill": "#c33c36",
            "scaleX": 1,
            "scaleY": 1,
            "opacity": 1
        },
        {
            "type": "square",
            "id": 1737904782741,
            "x": 200,
            "y": 478,
            "width": 200,
            "radius": 1,
            "height": 200,
            "angle": 0,
            "fontSize": 12,
            "fill": "#fefbfb",
            "scaleX": 1,
            "scaleY": 1,
            "opacity": 1
        },
        {
            "type": "square",
            "id": 1737904789421,
            "x": 400,
            "y": 478,
            "width": 200,
            "radius": 1,
            "height": 200,
            "angle": 0,
            "fontSize": 12,
            "fill": "#c33c36",
            "scaleX": 1,
            "scaleY": 1,
            "opacity": 1
        },
        {
            "type": "square",
            "id": 1737904793533,
            "x": 600,
            "y": 478,
            "width": 200,
            "radius": 1,
            "height": 200,
            "angle": 0,
            "fontSize": 12,
            "fill": "#fefbfb",
            "scaleX": 1,
            "scaleY": 1,
            "opacity": 1
        },
        {
            "type": "square",
            "id": 1737904807606,
            "x": 135,
            "y": 156,
            "width": 100,
            "radius": 1,
            "height": 100,
            "angle": 0,
            "fontSize": 12,
            "fill": "#bf9a5a",
            "scaleX": 5,
            "scaleY": 3,
            "opacity": 1
        },
        {
            "type": "text",
            "id": 1737904924671,
            "x": 206,
            "y": 265,
            "fill": "#10100f",
            "fontSize": 12,
            "radius": 1,
            "width": 77.7890625,
            "height": 13.559999999999997,
            "text": "Insert Text Here",
            "scaleX": 5,
            "scaleY": 5,
            "angle": 0,
            "opacity": 1
        },
        {
            "type": "square",
            "id": 1737905087070,
            "x": 135,
            "y": 121,
            "fill": "#fbff00",
            "fontSize": 12,
            "radius": 1,
            "width": 7,
            "height": 7,
            "scaleX": 5,
            "scaleY": 47.23828125,
            "angle": 0,
            "opacity": 1
        },
        {
            "type": "square",
            "id": 1737905123590,
            "x": 625,
            "y": 126,
            "width": 7,
            "radius": 1,
            "height": 7,
            "angle": 0,
            "fontSize": 12,
            "fill": "#fbff00",
            "scaleX": 5,
            "scaleY": 44.23828125,
            "opacity": 1
        },
        {
            "type": "square",
            "id": 1737905138854,
            "x": 100,
            "y": 128,
            "width": 7,
            "radius": 1,
            "height": 7,
            "angle": 0,
            "fontSize": 12,
            "fill": "#fbff00",
            "scaleX": 75,
            "scaleY": 5,
            "opacity": 1
        },
        {
            "type": "square",
            "id": 1737905184965,
            "x": 100,
            "y": 444,
            "width": 7,
            "radius": 1,
            "height": 7,
            "angle": 0,
            "fontSize": 12,
            "fill": "#fbff00",
            "scaleX": 75,
            "scaleY": 5,
            "opacity": 1
        }
    ],
    "backgroundColor": "#050505",
    "text": ""
}

export default MovieMadness;
