const PastelPalette = {
    "id": 0,
    "content": [
        {
            "type": "circle",
            "id": 1737519241733,
            "x": 420,
            "y": -28,
            "fill": "#f0bdb6",
            "fontSize": 12,
            "radius": 100,
            "width": 200,
            "height": 200,
            "angle": 0,
            "scaleX": 1,
            "scaleY": 1
        },
        {
            "type": "circle",
            "id": 1737519290805,
            "x": 201,
            "y": 89,
            "width": 200,
            "radius": 100,
            "height": 200,
            "angle": 0,
            "fontSize": 12,
            "fill": "#f0ead8",
            "scaleX": 1,
            "scaleY": 1
        },
        {
            "type": "circle",
            "id": 1737519292036,
            "x": -29,
            "y": 170,
            "width": 200,
            "radius": 100,
            "height": 200,
            "angle": 0,
            "fontSize": 12,
            "fill": "#f6f2ab",
            "scaleX": 1,
            "scaleY": 1
        },
        {
            "type": "circle",
            "id": 1737519293660,
            "x": 404,
            "y": 232,
            "width": 200,
            "radius": 100,
            "height": 200,
            "angle": 0,
            "fontSize": 12,
            "fill": "#d3c6a2",
            "scaleX": 1,
            "scaleY": 1
        },
        {
            "type": "circle",
            "id": 1737519294853,
            "x": -33,
            "y": 434,
            "width": 200,
            "radius": 100,
            "height": 200,
            "angle": 0,
            "fontSize": 12,
            "fill": "#d1feb8",
            "scaleX": 1,
            "scaleY": 1
        },
        {
            "type": "circle",
            "id": 1737519296077,
            "x": 649,
            "y": 324,
            "width": 200,
            "radius": 100,
            "height": 200,
            "angle": 0,
            "fontSize": 12,
            "fill": "#d9d5b7",
            "scaleX": 1,
            "scaleY": 1
        },
        {
            "type": "circle",
            "id": 1737519299453,
            "x": 426,
            "y": 455,
            "width": 200,
            "radius": 100,
            "height": 200,
            "angle": 0,
            "fontSize": 12,
            "fill": "#ebccff",
            "scaleX": 1,
            "scaleY": 1
        },
        {
            "type": "circle",
            "id": 1737519301692,
            "x": 1,
            "y": -60,
            "width": 200,
            "radius": 100,
            "height": 200,
            "angle": 0,
            "fontSize": 12,
            "fill": "#f8b8d2",
            "scaleX": 1,
            "scaleY": 1
        },
        {
            "type": "circle",
            "id": 1737519304580,
            "x": 180,
            "y": 336,
            "width": 200,
            "radius": 100,
            "height": 200,
            "angle": 0,
            "fontSize": 12,
            "fill": "#a5d7d8",
            "scaleX": 1,
            "scaleY": 1
        },
        {
            "type": "circle",
            "id": 1737519312684,
            "x": 637,
            "y": 88,
            "width": 200,
            "radius": 100,
            "height": 200,
            "angle": 0,
            "fontSize": 12,
            "fill": "#fac67c",
            "scaleX": 1,
            "scaleY": 1
        }
    ],
    "backgroundColor": "#d3f6fa",
    "text": ""
}
export default PastelPalette;