const TranquilBlue ={
    "id": 0,
    "content": [
        {
            "type": "circle",
            "id": 1738231239561,
            "x": -336,
            "y": -134,
            "fill": "#00abff",
            "fontSize": 12,
            "radius": 12,
            "width": 24,
            "height": 24,
            "scaleX": 20,
            "scaleY": 10,
            "angle": 0,
            "opacity": 1,
            "stroke": "#ccdde5",
            "strokeWidth": 1
        },
        {
            "type": "circle",
            "id": 1738233332291,
            "x": -313,
            "y": 455,
            "width": 24,
            "radius": 12,
            "height": 24,
            "angle": 0,
            "fontSize": 12,
            "fill": "#219dda",
            "scaleX": 20,
            "scaleY": 10,
            "opacity": 1,
            "stroke": "#ccdde5",
            "strokeWidth": 1
        },
        {
            "type": "circle",
            "id": 1738233335116,
            "x": 613,
            "y": -141,
            "width": 24,
            "radius": 12,
            "height": 24,
            "angle": 0,
            "fontSize": 12,
            "fill": "#3290ed",
            "scaleX": 20,
            "scaleY": 10,
            "opacity": 1,
            "stroke": "#ccdde5",
            "strokeWidth": 1
        },
        {
            "type": "circle",
            "id": 1738233342084,
            "x": 143,
            "y": -8,
            "width": 24,
            "radius": 12,
            "height": 24,
            "angle": 0,
            "fontSize": 12,
            "fill": "#0d5f87",
            "scaleX": 20,
            "scaleY": 10,
            "opacity": 1,
            "stroke": "#ccdde5",
            "strokeWidth": 1
        },
        {
            "type": "circle",
            "id": 1738233345964,
            "x": -308,
            "y": 158,
            "width": 24,
            "radius": 12,
            "height": 24,
            "angle": 0,
            "fontSize": 12,
            "fill": "#438ab0",
            "scaleX": 20,
            "scaleY": 10,
            "opacity": 1,
            "stroke": "#ccdde5",
            "strokeWidth": 1
        },
        {
            "type": "circle",
            "id": 1738233348252,
            "x": 169,
            "y": 272,
            "width": 24,
            "radius": 12,
            "height": 24,
            "angle": 0,
            "fontSize": 12,
            "fill": "#1aeae7",
            "scaleX": 20,
            "scaleY": 10,
            "opacity": 1,
            "stroke": "#ccdde5",
            "strokeWidth": 1
        },
        {
            "type": "circle",
            "id": 1738233350931,
            "x": 368,
            "y": 532,
            "width": 24,
            "radius": 12,
            "height": 24,
            "angle": 0,
            "fontSize": 12,
            "fill": "#0029ff",
            "scaleX": 20,
            "scaleY": 10,
            "opacity": 1,
            "stroke": "#ccdde5",
            "strokeWidth": 1
        },
        {
            "type": "circle",
            "id": 1738233353948,
            "x": 662,
            "y": 166,
            "width": 24,
            "radius": 12,
            "height": 24,
            "angle": 0,
            "fontSize": 12,
            "fill": "#7dd1fb",
            "scaleX": 20,
            "scaleY": 10,
            "opacity": 1,
            "stroke": "#ccdde5",
            "strokeWidth": 1
        },
        {
            "type": "square",
            "id": 1738233441965,
            "x": 150,
            "y": 110,
            "fill": "#235f9a",
            "fontSize": 12,
            "radius": 1,
            "width": 24,
            "height": 24,
            "scaleX": 20,
            "scaleY": 15,
            "angle": 0,
            "opacity": 1,
            "stroke": "#ccdde5"
        },
        {
            "type": "text",
            "id": 1738233545965,
            "x": 172,
            "y": 160,
            "fill": "#000000",
            "fontSize": 70,
            "radius": 1,
            "width": 453.76953125,
            "height": 79.09999999999998,
            "text": "Insert Text Here",
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "opacity": 1,
            "stroke": "#030303"
        }
    ],
    "backgroundColor": "#0bb3c2",
    "text": ""
}
export default TranquilBlue;