export const transitions = [
  { id: 'dissolve', title: 'Dissolve' },
  { id: 'fadeIn', title: 'Fade In' },
  { id: 'slideInLeft', title: 'Slide In Left' },
  { id: 'slideInRight', title: 'Slide In Right' },
  { id: 'slideInUp', title: 'Slide In Up' },
  { id: 'slideInDown', title: 'Slide In Down' },
  { id: 'slideOutLeft', title: 'Slide Out Left' },
  { id: 'slideOutRight', title: 'Slide Out Right' },
  { id: 'slideOutUp', title: 'Slide Out Up' },
  { id: 'slideOutDown', title: 'Slide Out Down' },
  { id: 'flipInX', title: 'Flip In (X Axis)' },
  { id: 'flipInY', title: 'Flip In (Y Axis)' },
  { id: 'flipOutX', title: 'Flip Out (X Axis)' },
  { id: 'flipOutY', title: 'Flip Out (Y Axis)' },
  { id: 'bounceIn', title: 'Bounce In' },
  { id: 'bounceOut', title: 'Bounce Out' },
  { id: 'zoomIn', title: 'Zoom In' },
  { id: 'zoomOut', title: 'Zoom Out' },
  { id: 'fadeOut', title: 'Fade Out' },
  { id: 'fadeInUp', title: 'Fade In Up' },
  { id: 'fadeInDown', title: 'Fade In Down' },
  { id: 'fadeInLeft', title: 'Fade In Left' },
  { id: 'fadeInRight', title: 'Fade In Right' },
  { id: 'rollIn', title: 'Roll In' },
  { id: 'rollOut', title: 'Roll Out' },
  { id: 'lightSpeedIn', title: 'Light Speed In' },
  { id: 'lightSpeedOut', title: 'Light Speed Out' },
  { id: 'hinge', title: 'Hinge' },
  { id: 'jackInTheBox', title: 'Jack In The Box' },
  { id: 'zoomInDown', title: 'Zoom In Down' },
  { id: 'zoomInUp', title: 'Zoom In Up' },
  { id: 'zoomInLeft', title: 'Zoom In Left' },
  { id: 'zoomInRight', title: 'Zoom In Right' },
  { id: 'zoomOutDown', title: 'Zoom Out Down' },
  { id: 'zoomOutUp', title: 'Zoom Out Up' },
  { id: 'zoomOutLeft', title: 'Zoom Out Left' },
  { id: 'zoomOutRight', title: 'Zoom Out Right' },
];
