export const transitions = [
  { id: 'dissolve', title: 'Dissolve' },
  {id: 'slideleft', title: 'Slide Left'},
  {id: 'slideright', title: 'Slide Right'},
  {id: 'slideup', title: 'Slide Up'},
  {id: 'slidedown', title: 'Slide Down'},
  {id: 'slidetopleft', title: 'Slide Top Left'},
  {id: 'slidetopright', title: 'Slide Top Right'},
  {id: 'slidebottomleft', title: 'Slide Bottom Left'},
  {id: 'slidebottomright', title: 'Slide Bottom Right'},  
  {id: 'scaleout', title: 'Scale Out'},
  {id: 'fliphorizontal', title: 'Flip Horizontal' },
  {id: 'flipvertical', title: 'Flip Vertical' },
  {id: 'rotateclockwise', title: 'Rotate Clockwise'},
  {id: 'rotatecounterclockwise', title: 'Rotate Counter Clockwise'},
];
